name: viva_journal
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  local_auth_android: ^1.0.49
  logger: ^2.5.0
  shared_preferences: ^2.2.2
  provider: ^6.1.4
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  local_auth: ^2.1.6
  crypto: ^3.0.3
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  carousel_slider: ^5.0.0
  path_provider: ^2.0.15 # SQLite
  sqflite: ^2.3.0
  image_picker: ^1.0.7
  flutter_sound: ^9.2.12
  speech_to_text: 7.0.0
  flutter_tts: ^4.2.2
  intl: ^0.19.0 # Latest version
  video_player: ^2.7.0
  cloud_firestore: ^5.6.5
  email_validator: ^3.0.0
  fl_chart: ^0.71.0
  flutter_quill: ^11.2.0
  flutter_quill_extensions: ^11.0.0
  share_plus: ^11.0.0
  pdf: ^3.11.3
  printing: ^5.14.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dotted_border: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/SF-Pro-Display-Regular.ttf
    - assets/fonts/SF-Pro-Display-Bold.ttf
    - assets/fonts/SF-Pro.ttf
    - assets/images/background.png
    - assets/images/HomeBarBG.png
    - assets/images/float_button.png
    - assets/images/HBstar.png
    - assets/on_screen_messages.txt
    - assets/images/Background_Calendar.png
    - assets/images/Rotate_Star.png
    - assets/images/Star.svg
    - assets/images/Left_arrow.png
    - assets/images/Right_arrow.png
    - assets/images/pencil_1.png
    - assets/images/pencil_2.png
    - assets/images/pencil_3.png
    - assets/images/pencil_4.png
    - assets/images/pencil_5.png
    - assets/images/pencil_6.png
    - assets/images/eraser.png
    - assets/images/StarBar.png
    - assets/images/small_left_arrow.png
    - assets/images/small_right_arrow.png
    - assets/images/Star0.png
    - assets/images/Star1.png
    - assets/images/Star2.png
    - assets/images/Star3.png
    - assets/images/Star4.png
    - assets/images/Star5.png
    - assets/images/Background_2.png
    - assets/images/Add_tag.png
    - assets/images/pfp.png
    - assets/images/streak.gif

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro.ttf
          weight: 500