name: viva_journal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/SF-Pro-Display-Regular.ttf
    - assets/fonts/SF-Pro-Display-Bold.ttf
    - assets/fonts/SF-Pro.ttf
    - assets/images/background.png
    - assets/images/HomeBarBG.png
    - assets/images/float_button.png
    - assets/images/HBstar.png
    - assets/images/google_logo.png
    - assets/on_screen_messages.txt
    - assets/images/Background_Calendar.png

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro.ttf
          weight: 500
