name: viva_journal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
<<<<<<< Updated upstream
=======
  shimmer: ^3.0.0
  intl: ^0.20.2

>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/SF-Pro-Display-Regular.ttf
    - assets/fonts/SF-Pro-Display-Bold.ttf
    - assets/fonts/SF-Pro.ttf
<<<<<<< Updated upstream
=======
    - assets/images/background.png
    - assets/images/HomeBarBG.png
    - assets/images/float_button.png
    - assets/images/HBstar.png
    - assets/images/google_logo.png
    - assets/on_screen_messages.txt
    - assets/images/Background_Calendar.png
<<<<<<< Updated upstream

>>>>>>> Stashed changes

=======
    - assets/images/Rotate_Star.png
    - assets/images/Star.svg
    - assets/images/Background_Calendar.png
    - assets/images/Left_arrow.png
    - assets/images/Right_arrow.png
    - assets/images/pencil_1.png
    - assets/images/pencil_2.png
    - assets/images/pencil_3.png
    - assets/images/pencil_4.png
    - assets/images/pencil_5.png
    - assets/images/pencil_6.png
    - assets/images/eraser.png
    - assets/images/Google.png
    - assets/images/small_left_arrow.png
    - assets/images/small_right_arrow.png
    - assets/images/empty_star.png
    - assets/images/yellow_star.png
    - assets/images/yellow_star1.png
    - assets/images/mid_star.png
    - assets/images/red_star.png
    - assets/images/red_star1.png
>>>>>>> Stashed changes
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro.ttf
          weight: 500

