name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Navigate to project directory
        working-directory: viva_journal/viva_journal
        run: pwd

      - name: Install dependencies
        working-directory: viva_journal/viva_journal
        run: flutter pub get

      - name: Analyze project source
        working-directory: viva_journal/viva_journal
        run: flutter analyze

      - name: Run tests
        working-directory: viva_journal/viva_journal
        run: flutter test

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Build the Flutter project
        working-directory: viva_journal/viva_journal
        run: |
          flutter pub get
          flutter build apk
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: viva_journal/viva_journal
