// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4yMqXGPtbvzYVWuvqek0aYpStgu5KY0',
    appId: '1:482258690101:web:b66a1164978dbeb1dbd17c',
    messagingSenderId: '482258690101',
    projectId: 'vivajournal-729f7',
    authDomain: 'vivajournal-729f7.firebaseapp.com',
    storageBucket: 'vivajournal-729f7.firebasestorage.app',
    measurementId: 'G-5HTD339KZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPxUB6Z4NR6dXrCjlGGNK0N-VKPF2oeaw',
    appId: '1:482258690101:android:4cdcc98a7523c5e3dbd17c',
    messagingSenderId: '482258690101',
    projectId: 'vivajournal-729f7',
    storageBucket: 'vivajournal-729f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaXQgKoMqBnEjjGLBKFSM6H8JO2F-UQn0',
    appId: '1:482258690101:ios:d74b3b8b213adf9adbd17c',
    messagingSenderId: '482258690101',
    projectId: 'vivajournal-729f7',
    storageBucket: 'vivajournal-729f7.firebasestorage.app',
    iosBundleId: 'com.example.vivaJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaXQgKoMqBnEjjGLBKFSM6H8JO2F-UQn0',
    appId: '1:482258690101:ios:d74b3b8b213adf9adbd17c',
    messagingSenderId: '482258690101',
    projectId: 'vivajournal-729f7',
    storageBucket: 'vivajournal-729f7.firebasestorage.app',
    iosBundleId: 'com.example.vivaJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS4yMqXGPtbvzYVWuvqek0aYpStgu5KY0',
    appId: '1:482258690101:web:154378f8a3b841d3dbd17c',
    messagingSenderId: '482258690101',
    projectId: 'vivajournal-729f7',
    authDomain: 'vivajournal-729f7.firebaseapp.com',
    storageBucket: 'vivajournal-729f7.firebasestorage.app',
    measurementId: 'G-NJ6HJM3S09',
  );
}
